//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookShop.Resources.StringConstants", typeof(StringConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected problem occurred while buying book..
        /// </summary>
        internal static string AddBookDialog_ErrorMessage_BuyBook_Message {
            get {
                return ResourceManager.GetString("AddBookDialog_ErrorMessage_BuyBook_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error buying book....
        /// </summary>
        internal static string AddBookDialog_ErrorMessage_BuyBook_Title {
            get {
                return ResourceManager.GetString("AddBookDialog_ErrorMessage_BuyBook_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide the author and the title of the book! Check if price is a valid value!.
        /// </summary>
        internal static string AddBookDialog_ErrorMessage_Validation_Message {
            get {
                return ResourceManager.GetString("AddBookDialog_ErrorMessage_Validation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating book....
        /// </summary>
        internal static string AddBookDialog_ErrorMessage_Validation_Title {
            get {
                return ResourceManager.GetString("AddBookDialog_ErrorMessage_Validation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer with the same name already exists!.
        /// </summary>
        internal static string AddCustomerDialog_ErrorMessage_CustomerAlreadyExists_Message {
            get {
                return ResourceManager.GetString("AddCustomerDialog_ErrorMessage_CustomerAlreadyExists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving customer....
        /// </summary>
        internal static string AddCustomerDialog_ErrorMessage_CustomerAlreadyExists_Title {
            get {
                return ResourceManager.GetString("AddCustomerDialog_ErrorMessage_CustomerAlreadyExists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name field is empty! Please fill name first!.
        /// </summary>
        internal static string AddCustomerDialog_ErrorMessage_NameFieldEmpty_Message {
            get {
                return ResourceManager.GetString("AddCustomerDialog_ErrorMessage_NameFieldEmpty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating customer....
        /// </summary>
        internal static string AddCustomerDialog_ErrorMessage_NameFieldEmpty_Title {
            get {
                return ResourceManager.GetString("AddCustomerDialog_ErrorMessage_NameFieldEmpty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string Category_Children {
            get {
                return ResourceManager.GetString("Category_Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        internal static string Category_Classic {
            get {
                return ResourceManager.GetString("Category_Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        internal static string Category_Drama {
            get {
                return ResourceManager.GetString("Category_Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantasy.
        /// </summary>
        internal static string Category_Fantasy {
            get {
                return ResourceManager.GetString("Category_Fantasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historic.
        /// </summary>
        internal static string Category_Historic {
            get {
                return ResourceManager.GetString("Category_Historic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        internal static string Category_Horror {
            get {
                return ResourceManager.GetString("Category_Horror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romantic.
        /// </summary>
        internal static string Category_Romantic {
            get {
                return ResourceManager.GetString("Category_Romantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific.
        /// </summary>
        internal static string Category_Scientific {
            get {
                return ResourceManager.GetString("Category_Scientific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sci-fi.
        /// </summary>
        internal static string Category_Scifi {
            get {
                return ResourceManager.GetString("Category_Scifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College.
        /// </summary>
        internal static string Qualification_College {
            get {
                return ResourceManager.GetString("Qualification_College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary School.
        /// </summary>
        internal static string Qualification_ElementarySchool {
            get {
                return ResourceManager.GetString("Qualification_ElementarySchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High School.
        /// </summary>
        internal static string Qualification_HighSchool {
            get {
                return ResourceManager.GetString("Qualification_HighSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        internal static string Qualification_University {
            get {
                return ResourceManager.GetString("Qualification_University", resourceCulture);
            }
        }
    }
}
